name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Install dependencies
      run: make
      
    - name: Run lint_check
      run: make lint-check
      
    - name: Run build
      run: make build
