name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make build
      
    - name: Run install
      run: make install
